version: '3.5'

services:
  phonebook:
    container_name: phonebook
    build: .
    command: ash -c "java -jar *.jar --spring.datasource.url=jdbc:mysql://phonebook-mysql:3306/phonebook?createDatabaseIfNotExist=true --spring.data.mongodb.host=phonebook-mongo"
    restart: always
    depends_on:
      - phonebook-mysql
      - phonebook-mongo
    ports:
      - 8080:8080
    networks:
      - snapp
  phonebook-mysql:
    container_name: phonebook-mysql
    image: mysql:8.0.14
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - snapp
    environment:
      MYSQL_ROOT_PASSWORD: root
  phonebook-mongo:
    container_name: phonebook-mongo
    image: mongo:4.4
    restart: always
    networks:
      - snapp
networks:
  snapp:
    driver: bridge


